Fast api assignment 1
vaishnavirtp/Assignments pull request #7
Opened 2023-07-11 07:07 UTC by vaishnavirtp

2023-07-12 07:35 UTC, ropali-munshi requested changes

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/__pycache__/books.cpython-310.pyc
You should avoid committing these files as these are cache files. Read about `.gitignore` file

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +models.Base.metadata.create_all(bind=engine)
What is this line? & what's it doing inside the router file?

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +def get_db():
This func should not be part of router code.

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    return HTTPException(status_code=201, detail=f"Successfully created the task")
You are returning an `Exception` for a successful request!. So many things wrong in single line.
1. You should always raise an exception and not return it. (Actually not required here).
2. HTTPException should only be raised in case of an error not for a successful request.
3. You always return a JSON request and not HTTPException for successful request

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    return HTTPException(status_code=200, detail="Successfully updated the task")
Same mistake here

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    return HTTPException(status_code=200, detail="Successfully deleted the task")
Same mistake here

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    return HTTPException(status_code=200, detail="Successfully deleted all the task")
Same mistake here

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +def update_task(task_id: int, task: Task, db: Session = Depends(get_db)):
While updating a Task user will have to provide all the details again while making an update request which is not desirable. Only few details should be allowed to update.

2023-07-12 07:35 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    task_model.name = task.name
Do not add fields manually if the model fields and Task schema fields are the same. Read about `*args` & `**kwargs` in Python.

2023-07-12 07:35 UTC, ropali-munshi commented on Debug-module/Assignment 1/README.md
Why these other assignment files are deleted?

2023-07-12 09:15 UTC, vaishnavirtp commented on Debug-module/Assignment 1/README.md
Wanted to keep only that code on that branch, wont delete next time.

2023-07-12 11:02 UTC, ropali-munshi commented on Debug-module/Assignment 1/README.md
@vaishnavirtp This is not how it works. If delete the code from this branch and merge it to main then it will delete those files from main branch as well

2023-07-12 11:12 UTC, ropali-munshi requested changes

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/__pycache__/books.cpython-310.pyc
These cache files are still not removed.

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/app/schemas/schemas.py
> +    priority: str = Optional[str]
You should use the `Priority` enum type here instead of str

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    except Exception as e:
This is really a bad way to handle a exception, read this https://stackoverflow.com/a/10594142/6832201

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    except:
This is even worse.

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +    except:
Same here

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +        return HTTPException(status_code=404, detail=f"Task Not found.")
This is not going to work. You are returning an `Exception`. Exceptions are never returned only raised. This not going to work as expected and result in some really bad bugs.

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +        return HTTPException(status_code=400, detail=f"Some error occured.")
Avoid returning exception

2023-07-12 11:12 UTC, ropali-munshi commented on TODO Api/app/routes/router.py
> +        return HTTPException(status_code=404, detail=f"Task Not found.")
Avoid returning exception

2023-07-13 06:21 UTC, ropali-munshi requested changes

2023-07-13 06:21 UTC, ropali-munshi commented on TODO Api/app/database/database.py
> +Base.metadata.create_all(bind=engine)
Do you understand what this line does?

2023-07-13 06:21 UTC, ropali-munshi commented on TODO Api/app/utils/exceptions.py
> +class RaiseError(Exception, ABC):
Why do you need this class?

2023-07-13 06:21 UTC, ropali-munshi commented on TODO Api/app/utils/exceptions.py
> +    def get_message_for_dev(self):
Avoid writing method names like this by using conjunction & prepositions. This could be simply written as `dev_error` or `dev_messag`

2023-07-13 06:21 UTC, ropali-munshi commented on TODO Api/tasks.db
This file should not be commited.

2023-07-18 06:20 UTC, ropali-munshi approved these changes

2023-07-20 05:11 UTC, closed without merging